---
- name: "Ensure packages are present"
  yum:
    name: "{{ pkg_list }}"
    state: present
  become: yes

- name: "Ensure index.html is present"
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes

- name: "Ensure httpd started and enabled"
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ svc_list }}"
  become: yes

- name : "Whitelist httpd"
  firewalld:
    service: httpd
    state: enabled
    permanent: true
    immediate: true
  become: yes
